int1 = int(input("Enter integer 1: "))
int2 = int(input("Enter integer 1: "))
float1 = float(input("Enter float 1: "))
float2 = float(input("Enter float 2: "))
print("\n*******ARITHMETIC OPERATIONS ON INTEGERS*******")
print("ADDITION: ",int1,' + ',int2,' = ',int1+int2)
print("SUBTRACTION: ",int1,' - ',int2,' = ',int1-int2)
print("MULTIPLICATION: ",int1,' * ',int2,' = ',int1*int2)
print("DIVISION: ",int1,' / ',int2,' = ',int1/int2)
print("FLOOR DIVISION: ",int1,' // ',int2,' = ',int1//int2)
print("EXPONENTIATION: ",int1,' ^ ',int2,' = ',int1**int2)
print("\n*******ARITHMETIC OPERATIONS ON FLOATING POINT*******")
print("ADDITION: ",float1,' + ',float2,' = ',float1+float2)
print("SUBTRACTION: ",float1,' - ',float2,' = ',float1-float2)
print("MULTIPLICATION: ",float1,' * ',float2,' = ',float1*float2)
print("DIVISION: ",float1,' / ',float2,' = ',float1/float2)
print("FLOOR DIVISION: ",float1,' // ',float2,' = ',float1//float2)
print("EXPONENTIATION: ",float1,' ^ ',float2,' = ',float1**float2)
