languages=['Hindi', 'English', 'Bengali', 'Oriya', 'Telugu', 'Marathi', 'Malayalam']
print("i.	",languages [2])
print("ii.	",languages [-3])
print("iii.	",languages [2:5])
print("iv.	",languages [2:5:2])
print("v.	",languages [:5])
print("vi.	",languages [3:])
print("vii.	",languages [::2])
print("viii.	",languages [::-2])
print("ix.	",languages [-5:-2])
print("x.	",languages [5:2:-1])
print("xi.	",languages [-2:-5:-1])
print("xii.	",languages [-2:-5:-2])